<?php
return [
    'stopwords' => [
        'poliklinik' => ['apa', 'itu', 'adalah', 'di', 'ke'],
        'layanan' => ['apa', 'itu', 'berapa', 'dan'],
        'faq' => ['bagaimana', 'mohon', 'boleh', 'saya'],
        'ruang_rawat' => ['apa', 'itu', 'berapa', 'dan'],
        'rapid_swab' => ['apa', 'itu', 'berapa'],
    ],
    'rawat_jalan' => [
        'poliklinik penyakit dalam' => ['penyakit dalam', 'klinik penyakit dalam', 'internis'],
        'poliklinik jantung' => ['klinik jantung', 'jantung', 'kardiologi'],
        'poliklinik bedah' => ['klinik bedah', 'bedah', 'operasi'],
        'poliklinik syaraf' => ['klinik syaraf', 'neurologi', 'saraf', 'syarap'],
        'poliklinik tht' => ['klinik tht', 'telinga hidung tenggorokan', 'tht'],
        'poliklinik gigi' => ['klinik gigi', 'gigi', 'dokter gigi'],
        'poliklinik paru' => ['klinik paru', 'paru-paru', 'pulmonologi'],
        'poliklinik kandungan' => ['klinik kandungan', 'obgyn', 'kandungan', 'kehamilan'],
        'poliklinik jiwa' => ['klinik jiwa', 'psikiatri', 'kejiwaan', 'psikiater'],
        'poliklinik anak' => ['klinik anak', 'anak', 'pediatri'],
        'poliklinik fisioterapi' => ['klinik fisioterapi', 'fisioterapi', 'terapi fisik'],
        'poliklinik komplementer' => ['klinik komplementer', 'komplementer', 'alternatif'],
        'poliklinik kulit dan kelamin' => ['klinik kulit', 'klinik kelamin', 'dermatologi', 'kelamin'],
        'poliklinik mata' => ['klinik mata', 'mata', 'oftalmologi', 'spesialis mata'],
        'poliklinik ortopedi' => ['klinik ortopedi', 'ortopedi', 'tulang'],
        'prosedur pendaftaran' => ['pendaftaran', 'daftar berobat', 'cara mendaftar', 'registrasi'],
        'layanan rawat jalan' => ['rawat jalan', 'layanan rawat', 'poli tersedia'],
    ],
    'layanan' => [
        'medical checkup' => ['apa itu medical checkup', 'tarif medical checkup', 'berapa biaya medical checkup', 'mcu'],
        'paket 1' => ['detail paket 1', 'info paket 1', 'paket satu'],
        'paket 2' => ['detail paket 2', 'info paket 2', 'paket dua'],
        'paket 3' => ['detail paket 3', 'info paket 3', 'paket tiga'],
        'paket 4' => ['detail paket 4', 'info paket 4', 'paket empat'],
        'paket 5' => ['detail paket 5', 'info paket 5', 'paket lima'],
        'paket 6' => ['detail paket 6', 'info paket 6', 'paket enam'],
        'paket 7' => ['detail paket 7', 'info paket 7', 'paket tujuh'],
        'paket 8' => ['paket 8', 'informasi rikkes', 'pemeriksaan kesehatan'],
        'radiologi' => ['apa itu radiologi', 'pemeriksaan radiologi'],
        'laboratorium' => ['apa itu laboratorium', 'lab', 'pemeriksaan lab'],
        'eswl' => ['apa itu eswl', 'extracorporeal shock wave lithotripsy'],
        'kemoterapi' => ['apa itu kemoterapi', 'kemo', 'pengobatan kanker'],
        'radioterapi' => ['apa itu radioterapi', 'terapi radiasi'],
        'onkologi' => ['apa itu onkologi', 'kanker', 'pengobatan kanker'],
        'ct scan' => ['apa itu ct scan', 'scan ct', 'pemindaian'],
        'cathlab' => ['apa itu cathlab', 'kateterisasi jantung'],
        'echokardiografi' => ['apa itu echokardiografi', 'ekg jantung'],
        'treadmill' => ['apa itu treadmill', 'tes treadmill', 'stress test'],
        'pemeriksaan jiwa' => ['pemeriksaan medis kejiwaan', 'apa itu medis kejiwaan', 'psikiatri'],
        'endoskopi' => ['apa itu endoskopi', 'pemeriksaan endoskopi'],
        'bpjs' => ['asuransi bpjs', 'pembayaran bpjs', 'bpjs kesehatan'],
    ],
    'faq' => [
        'prosedur pendaftaran' => ['cara daftar', 'bagaimana cara mendaftar', 'pendaftaran pasien', 'alur pendaftaran', 'registrasi'],
        'biaya perawatan' => ['berapa biaya perawatan', 'biaya pengobatan', 'tarif perawatan', 'harga pengobatan'],
        'layanan kesulitan' => ['kesulitan mendapatkan layanan', 'kesulitan akses layanan', 'kendala layanan kesehatan'],
        'komitmen layanan' => ['mengapa kami selalu terdepan', 'komitmen kami', 'motto layanan kami', 'visi misi'],
        'jam operasional' => ['jam buka', 'jadwal poliklinik', 'waktu operasional'],
        'dokter spesialis' => ['spesialis apa saja', 'daftar dokter', 'dokter spesialis tersedia'],
    ],
    'rapid_swab' => [
        'tarif rapid swab' => ['rapid test', 'tes antigen', 'swab antigen', 'rapid antigen', 'tarif rapid test', 'biaya swab antigen'],
    ],
    'ruang_rawat' => [
        'tarif rawat inap' => ['tarif kelas ruang rawat inap', 'biaya kamar inap', 'harga rawat inap', 'tarif perawatan kamar'],
    ],
];
?>